fake_friends = [
    {'name': 'Alex Johnson',
    'image': "blankProfile.webp",  
    },
    {'name': 'Emma Thompson',
    'image': "blankProfile.webp",  
    },
    {'name': 'Michael Brown',
    'image': "blankProfile.webp",  
    },
    {'name': 'Sophia Martinez',
    'image': "blankProfile.webp",  
    },
    {'name': 'Isabella Davis',
    'image': "blankProfile.webp",  
    },
    {'name': 'Ethan Wilson',
    'image': "blankProfile.webp", 
    },
    {'name': 'Olivia Garcia',
    'image': "blankProfile.webp", 
    },
    {'name': 'Liam Anderson',
    'image': "blankProfile.webp",

    },
]
